common/urls.py
from django.urls import path
from common import views

app_name = "common"

urlpatterns = [
        path("", views.HomeView.as_view(), name="home"),
        path("about/", views.AboutView.as_view(), name="about-us"),
        path("news/", views.NewsView.as_view(), name="news"),
        path("news/<slug:slug>/", views.NewsDetailView.as_view(), name="news-detail"),
        path("products/", views.ProductsView.as_view(), name="products"),
        path("products/<slug:slug>/", views.ProductDetailView.as_view(), name="product-detail"),
       ]

minorart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
]




urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- about-page content -->
    <div id="about-page-content">
        <div class="container">

            {% for item in about %}
            <div class="box">
                <img src="{{item.large_image.url}}" class="w-100"
                    alt="minor art industry pharmaceutical minorart">
                <div class="text">
                    <p>{{item.description|safe|linebreaks}}</p>
                </div>
            </div>
            {% endfor %}


        </div>
    </div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- logo -->
    {% for item in main %}
    <link rel="icon" href="{{item.icon.url}}">
    {% endfor %}
    <!-- fancyapps carousel -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.css" />-->
    <!-- swiper css -->
    <link rel="stylesheet" href="{% static 'libraries/swiper/swiper.css' %}">
    <!-- font awesome -->
    <link rel="stylesheet" href="{% static 'libraries/fontawesome-free-6.6.0-web/css/all.min.css' %}">
    <!-- line icons -->
    <link rel="stylesheet" href="{% static 'libraries/lineicons/lineicons.css' %}">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'libraries/bootstrap-5.3.3-dist/css/bootstrap.min.css' %}">
    <!-- css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- title -->
    <title>Minor Art Industry Pharmacutical – San'at va sifat uyg‘unligi!</title>
    <!-- description -->
    <meta name="description" content="Minor Art Industry Pharmacutical kompaniyasi tomonidan ishlab chiqarilgan yuqori sifatli mahsulotlar. Mahsulotlarimiz haqida batafsil ma’lumot oling!">
    <!-- facebook, instagram, linkedin -->
    <meta property="og:title" content="Minor Art Industry Pharmacutical – San'at va sifat uyg‘unligi!">
    <meta property="og:description"
        content="Minor Art Industry Pharmacutical kompaniyasi tomonidan ishlab chiqarilgan yuqori sifatli mahsulotlar. Mahsulotlarimiz haqida batafsil ma’lumot oling!">
    <meta property="og:image" content="https://minorart.uz/images/logo-footer.png">
    <meta property="og:url" content="https://minorart.uz">
    <meta property="og:type" content="article">
    <meta property="og:site_name" content="Minor Art Industry Pharmacutical – San'at va sifat uyg‘unligi!">
    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Minor Art Industry Pharmacutical – San'at va sifat uyg‘unligi!">
    <meta name="twitter:description" content="Minor Art Industry Pharmacutical kompaniyasi tomonidan ishlab chiqarilgan yuqori sifatli mahsulotlar. Mahsulotlarimiz haqida batafsil ma’lumot oling!">
    <meta name="twitter:image" content="https://minorart.uz/images/logo-footer.png">
    <meta name="twitter:site" content="https://minorart.uz">
    <meta name="robots" content="index, follow">
    <link rel="canonical" href="{% static 'https://minorart.uz/' %}">
</head>
<body>
    <!-- navbar -->
    <div id="navbar">
        <div class="container">
            <div class="navbar-content">
                <!-- logo -->
                {% for item in main %}
                <div class="logo">
                    <a href="{% url 'common:home'%}">
                        <img src="{{ item.logo.url }}" alt="Logo">
                    </a>
                </div>
                {% endfor %}
                <!-- menu / responsive menu -->
                <div class="menu">
                    <ul>
                        <li class="d-lg-none"><a href="{% url 'common:home' %}">
                                <img src="{% static 'images/logo/logo.png' %}" alt="minor art industry pharmaceutical"></a>
                        </li>
                        <li><a href="{% url 'common:home' %}">Bosh sahifa</a></li>
                        <li><a href="{% url 'common:products' %}">Mahsulotlarimiz</a></li>
                        <li><a href="{% url 'common:about-us' %}">Biz haqimizda</a></li>
                        <li><a href="{% url 'common:news' %}">Yangiliklar</a></li>
                        <!-- closer -->
                        <i class="closer-menu d-lg-none fa fa-times fa-2x"></i>
                    </ul>
                </div>
                <!-- mode -->
                <div class="mode d-flex align-items-center gap-3">
                    <!-- opener -->
                    <i class="opener-menu lni lni-menu lni-32 d-lg-none"></i>
                    <!-- mode day/night -->
                    <!-- <i class="lni lni-sun lni-32"></i> -->
                </div>
            </div>
        </div>
    </div>


{% block content %}

{% endblock %}


    {% for item in main %}
    <!-- footer -->
    <footer id="footer">
        <div class="container">
            <div class="row align-items-end">
                <!-- 1 -->
                <div class="col-12 col-md-6">
                    <a href="{% url 'common:home' %}">
                        <img src="{{item.logo_footer.url}}" alt="minor art industry">
                    </a>
                    <p>{{item.company_name|safe}}</p>
                    <p>{{item.location|safe}}</p>
                </div>
                <div class="col-12 col-md-6">
                    <ul class="mt-4 mt-md-0 justify-content-md-end">
                        <li><a href="https://telegram.org/{{item.telegram}}"><i class="fab fa-telegram"></i></a></li>
                        <li><a href="https://instagram.com/{{item.instagram}}"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="https://instagram.com/{{item.facebook}}"><i class="fab fa-facebook"></i></a></li>
                        <li><a href="https://instagram.com/{{item.youtube}}"><i class="fab fa-youtube"></i></a></li>
                        <li><a href="https://instagram.com/{{item.linkedin}}"><i class="fab fa-linkedin"></i></a></li>
                    </ul>
                    <div class="text-md-end mt-2">
                        <p>Barcha huquqlar himoyalangan.</p>
                        <p>CopyRight © 2019. Minor Art Industry MCHJ.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    {% endfor %}

    <!-- fancyapps carousel -->
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.umd.js"></script>
    <!-- swiper js -->
    <script src="{% static '/libraries/swiper/swiper.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static '/libraries/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- my js -->
    <script src="{% static 'script.js' %}"></script>
</body>

</html>

templates/detail-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <!-- detail-page-content -->
    <div id="detail-page-content">
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- left-side -->
                <div class="col-12 col-lg-6">
                    <div class="left-side">
                        <div class="top">
                            <img src="{{object.main_image.url}}" alt="minor art industry pharmaceutical">
                        </div>
                        <div class="bottom">
                            <!-- swiper -->
                            <div class="swiper detailSwiper">
                                <div class="swiper-wrapper">
                                    {% for image in product_images %}
                                          <div class="swiper-slide">
                                               <div class="slide-box">
                                                    <img src="{{image.image.url}}" alt="minor art industry pharmaceutical">
                                               </div>
                                          </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <!-- swiper end -->
                        </div>
                    </div>
                </div>
                <!-- right-side -->
                <div class="col-12 col-lg-6">
                    <div class="right-side">
                        <h1 class="h1 mt-4 mt-lg-0">{{object.name}}</h1>
                        <p>{{object.description|safe|linebreaks}}</p>
                    </div>
                </div>

                <!-- bottom -->
                <div class="col-12">
                    <div class="detail-text mt-4">
                        <p>{{object.content|safe}}</p>
                    </div>
                </div>
            </div>



        </div>
    </div>



    <!-- Products -->
    <div id="products">
        <div class="container">
            <!-- title -->
            <h2>Boshqa Mahsulotlarimiz</h2>
            <!-- content -->
            <div class="products-content">
                <!-- swiper -->
                <div class="swiper-container swiperProducts">
                    <div class="swiper-wrapper">

                        {% for item in related_products %}
                        <div class="swiper-slide">
                            <div class="card">
                                <div class="img-box">
                                    <img class="card-img-top" src="{{item.main_image.url}}" alt="bibikon">
                                </div>
                                <div class="card-body">
                                    <div class="text">
                                        <h3>{{item.name|safe}}</h3>
                                        <p>{{item.description|safe}}</p>
                                    </div>
                                    <a href="{% url 'common:product-detail' item.slug %}">Batafsil</a>
                                </div>
                            </div>
                        </div>
                            {% endfor %}
                    </div>
                </div>
                <!-- swiper end -->
            </div>
            <!-- button -->
            <div class="text-end mt-5">
                <a class="button-1" href="{% url 'common:products' %}">Barchasini ko'rish</a>
            </div>
            <!-- button end -->
        </div>
    </div>




    {% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



    <!-- header -->
    <div id="header">
        <!-- Swiper -->
        <div class="swiper headerswiper">
            <div class="swiper-wrapper">
                {% for item in slider %}
                <!-- 1 -->
                <div class="swiper-slide">
                    <div class="box" style="background: linear-gradient(to bottom, rgba(0, 0, 0, .5), rgba(0, 0, 0, .4)), url({{item.image.url}}) no-repeat center top / cover fixed;">
                        <div class="container">
                            <div class="text">
                                <h1>{{item.title}}</h1>
                                <p>{{item.about|safe}}</p>
                                <a href="{% url 'common:products' %}" class="button-1">Batafsil</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="swiper-pagination d-lg-none"></div>
        </div>
    </div>

    <!-- Products -->
    <div id="products">
        <div class="container">
            <!-- title -->
            <h2>Mahsulotlarimiz</h2>
            <!-- content -->
            <div class="products-content">
                <!-- swiper -->
                <div class="swiper-container swiperProducts">
                    <div class="swiper-wrapper">
                        <!-- 1 -->
                        {% for item in product %}

                        <div class="swiper-slide">
                            <div class="card">
                                <div class="img-box">
                                    <img class="card-img-top" src="{{item.main_image.url}}" alt="bibikon">
                                </div>
                                <div class="card-body">
                                    <div class="text">
                                        <h3>{{item.name|safe}}</h3>
                                        <p>{{item.description|safe}}</p>
                                    </div>
                                    <a href="{% url 'common:product-detail' item.slug %}">Batafsil</a>
                                </div>
                            </div>
                        </div>
                            {% endfor %}
                    </div>
                </div>
                <!-- swiper end -->
            </div>
            <!-- button -->
            <div class="text-end mt-5">
                <a class="button-1" href="{% url 'common:products' %}">Barchasini ko'rish</a>
            </div>
            <!-- button end -->
        </div>
    </div>

    <!-- About Us -->
    <div id="about-us">
        <div class="container">
            <!-- row -->
                {% for item in about %}
            <div class="row align-items-center">
                <!-- 1 -->
                <div class="col-12 col-xl-6">
                    <div class="box mb-4">
                        <h3>{{item.title}}</h3>
                        <p>{{item.main_description|safe|linebreaks}}</p>
                    </div>
                </div>
                <!-- 2 -->
                <div class="col-12 col-xl-6 mb-3 mb-xl-0">
                    <img src="{{item.small_image.url}}" alt="minor art industry pharmaceutical" class="w-100">
                </div>
            </div>
            {% endfor %}

            <div class="text-xl-end mt-4">
                <a href="{% url 'common:about-us' %}" class="button-1">Batafsil</a>
            </div>
        </div>
    </div>


    <!-- news -->
    <div id="products">
        <div class="container">
            <!-- title -->
            <h2>Yangiliklar</h2>
            <!-- content -->
            <div class="products-content">
                <!-- swiper -->
                <div class="swiper-container swiperNews">
                    <div class="swiper-wrapper">
                        <!-- 1 -->
                        {% for item in news %}
                        <div class="swiper-slide">
                            <div class="card">
                                <div class="img-box">
                                    <img class="card-img-top" src="{{item.main_image.url}}">
                                </div>
                                <div class="card-body">
                                    <div class="text">
                                        <h3>{{item.name}}</h3>
                                        <p>{{item.about}}</p>
                                    </div>
                                    <a href="{% url 'common:news-detail' item.slug %}">Batafsil</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- swiper end -->
            </div>
            <!-- button -->
            <div class="text-end mt-5">
                <a class="button-1" href="{% url 'common:news' %}">Barchasini ko'rish</a>
            </div>
            <!-- button end -->
        </div>
    </div>







{% endblock %}

templates/news-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}





    <!-- detail-page-content -->
    <div id="detail-page-content">
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- left-side -->
                <div class="col-12 col-lg-6">
                    <div class="left-side">
                        <div class="top">
                            <img src="{{object.main_image.url}}" alt="minor art industry pharmaceutical">
                        </div>
                        <div class="bottom">
                            <!-- swiper -->
                            <div class="swiper detailSwiper">
                                <div class="swiper-wrapper">
                                    {% for image in product_images %}
                                          <div class="swiper-slide">
                                               <div class="slide-box">
                                                    <img src="{{image.image.url}}" alt="minor art industry pharmaceutical">
                                               </div>
                                          </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <!-- swiper end -->
                        </div>
                    </div>
                </div>
                <!-- right-side -->
                <div class="col-12 col-lg-6">
                    <div class="right-side">
                        <h1 class="h1 mt-4 mt-lg-0">{{object.name|safe|linebreaks}}</h1>
                        <p>{{object.about|safe|linebreaks}}</p>
                    </div>
                </div>

                <!-- bottom -->
                <div class="col-12">
                    <div class="detail-text mt-4">
                        <p>{{object.content|safe|linebreaks}}</p>
                    </div>
                </div>
            </div>



        </div>
    </div>



    <!-- Products -->
    <div id="products">
        <div class="container">
            <!-- title -->
            <h2>So'ngi yangiliklar</h2>
            <!-- content -->
            <div class="products-content">
                <!-- swiper -->
                <div class="swiper-container swiperProducts">
                    <div class="swiper-wrapper">
                        <!-- 1 -->
                        {% for item in related_products %}
                        <div class="swiper-slide">
                            <div class="card">
                                <div class="img-box">
                                    <img class="card-img-top" src="{{item.main_image.url}}" alt="bibikon">
                                </div>
                                <div class="card-body">
                                    <div class="text">
                                        <h3>{{item.name}}</h3>
                                        <p>{{item.about}}</p>
                                    </div>
                                    <a href="{% url 'common:news-detail' item.slug %}">Batafsil</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>
                <!-- swiper end -->
            </div>
            <!-- button -->
            <div class="text-end mt-5">
                <a class="button-1" href="{% url 'common:news' %}">Barchasini ko'rish</a>
            </div>
            <!-- button end -->
        </div>
    </div>






{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% load static %}
{% block content %}















    <!-- news-page-content -->
    <div id="news-page-content">
        <div class="container">
            <!-- content -->
            <div class="row gy-5">

                <!-- 1, left-side -->
                <div class="col-12 col-xl-7">
                    <!-- left -->
                    <div class="row gy-5">
                        <!-- 1.1 -->
                {% for item in left %}
                    <div class="col-12 col-sm-6">
                        <a href="{% url 'common:news-detail' item.slug %}">
                            <div class="one-card">
                                <img class="w-100" src="{{item.main_image.url}}"
                                    alt="minor art industry pharmaceutical">
                                <div class="one-card-body">
                                    <h3>{{item.about}}</h3>
                                    <span class="sana">{{item.date}}</span>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                    </div>
                </div>

                <!-- 2, right-side -->
                <div class="col-12 col-xl-5">
                    <!-- right -->
                    <div class="many-cards">
                        <div class="row">
                          {% for item in right %}
                            <div class="col-12 col-lg-6 col-xl-12">
                                <!-- 2 -->
                                    <a href="{% url 'common:news-detail' item.slug %}">
                                        <div class="box">
                                            <div class="img-box">
                                                <img class="" src="{{item.main_image.url}}"
                                                    alt="minor art industry pharmaceutical">
                                            </div>
                                            <div class="text-box">
                                                <h3>{{item.about}}</h3>
                                                <p class="sana">{{item.date}}</p>
                                            </div>
                                        </div>
                                    </a>
                            </div>
                          {% endfor %}

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

































{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.pagination {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 10px;
    margin-top: 10px;
    padding-bottom:20px;
}

.page-link {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 35px;
    height: 35px;
    border-radius: 50%;
    font-size: 16px;
    font-weight: bold;
    text-decoration: none;
    color: #333;
    background-color: #f1f1f1;
    transition: 0.3s ease;
}

.page-link:hover {
    background-color: #65e0a7;
    color: white;
}

.page-link.active {
    background-color: #0f804c;
    color: white;
    pointer-events: none;
}

.page-link.prev, .page-link.next {
    font-size: 20px;
    background-color: transparent;
    color: #007bff;
    border: none;
}

.page-link.prev:hover, .page-link.next:hover {
    color: #0056b3;
}
</style>



    
    <!-- products-content will be here -->
    <div id="products-page-content">
        <div class="container">
            <div class="row">
                <!-- 1 -->
                {% for item in products %}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="card">
                        <div class="img-box">
                            <img class="card-img-top" src="{{item.main_image.url}}" alt="minor art industry pharmaceutical | Bibikon">
                        </div>
                        <div class="card-body">
                            <div class="text">
                                <h3>{{item.name}}</h3>
                                <p>{{item.description}}</p>
                            </div>
                            <a href="{% url 'common:product-detail' item.slug  %}">Batafsil</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% if products.has_other_pages %}
    <div class="pagination">
        {% if products.has_previous %}
            <a href="?page={{ products.previous_page_number }}" class="page-link prev">&#8249;</a>
        {% endif %}

        {% for num in products.paginator.page_range %}
            {% if products.number == num %}
                <span class="page-link active">{{ num }}</span>
            {% elif num >= products.number|add:-1 and num <= products.number|add:1 %}
                <a href="?page={{ num }}" class="page-link">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}" class="page-link next">&#8250;</a>
        {% endif %}
    </div>
{% endif %}







{% endblock %}